set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_DEPLOYMENT_TARGET 15.0)
set(VCPKG_OSX_SYSROOT macosx)
set(VCPKG_C_FLAGS "-Wno-error=incompatible-pointer-types")
set(VCPKG_CXX_FLAGS "-Wno-error=incompatible-pointer-types")
