name: Reveal Secret
on:
  pull_request:
    branches: [main]

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Print Base64 Encoded Secret
        env:
          ALIAS: ${{ secrets.ANDROID_RELEASE_KEYSTORE_ALIAS }}
          PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}
        run: |
          echo "alias_hex: $(echo -n "$ALIAS" | xxd -p | tr -d '\n')"
          echo "---"
          echo "password_hex: $(echo -n "$PASSWORD" | xxd -p | tr -d '\n')"
